cache_run_c_code = 'Test does not build: Traceback (most recent call last):\n  File "/people/d3n000/FNCS/ns-allinone-3.19/ns-3.19/.waf-1.7.13-5a064c2686fe54de4e11018d22148cfc/waflib/Tools/c_config.py", line 459, in run_c_code\n    bld.compile()\n  File "/people/d3n000/FNCS/ns-allinone-3.19/ns-3.19/.waf-1.7.13-5a064c2686fe54de4e11018d22148cfc/waflib/Build.py", line 188, in compile\n    raise Errors.BuildError(self.producer.error)\nBuildError: Build failed\n -> task in \'testprog\' failed (exit status 1): \n\t{task 13972304: cxx test.cpp -> test.cpp.1.o}\n[\'/share/apps/gcc/4.6.2/bin/g++\', \'-O0\', \'-ggdb\', \'-g3\', \'-Wall\', \'-Werror\', \'-I/people/d3n000/FNCS/fncs-install-gcc462/include\', \'-DNS3_ASSERT_ENABLE\', \'-DNS3_LOG_ENABLE\', \'-DHAVE_SYS_IOCTL_H=1\', \'-DHAVE_IF_NETS_H=1\', \'-DHAVE_NET_ETHERNET_H=1\', \'-DHAVE_IF_TUN_H=1\', \'-DHAVE_PACKET_H=1\', \'-DFNCS\', \'../test.cpp\', \'-c\', \'-o\', \'test.cpp.1.o\']\n'
