cache_run_c_code = 'Test does not build: Traceback (most recent call last):\n  File "/people/d3n000/FNCS/ns-allinone-3.19/ns-3.19/.waf-1.7.13-5a064c2686fe54de4e11018d22148cfc/waflib/Tools/c_config.py", line 459, in run_c_code\n    bld.compile()\n  File "/people/d3n000/FNCS/ns-allinone-3.19/ns-3.19/.waf-1.7.13-5a064c2686fe54de4e11018d22148cfc/waflib/Build.py", line 188, in compile\n    raise Errors.BuildError(self.producer.error)\nBuildError: Build failed\n -> task in \'testprog\' failed (exit status 1): \n\t{task 38094224: cxxprogram test.cpp.1.o -> testprog}\n[\'/share/apps/gcc/4.6.2/bin/g++\', \'test.cpp.1.o\', \'-o\', \'/people/d3n000/FNCS/ns-allinone-3.19/ns-3.19/build/.conf_check_a3fe06f501caf0b0ea61b2cfde1521cd/testbuild/testprog\', \'-Wl,-Bstatic\', \'-Wl,-Bdynamic\', \'-L/people/d3n000/FNCS/fncs-install-gcc462/lib\', \'-lfncs\']\n'
